[package]
name = "bevy_ggrs_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_asset_loader = "0.8"
bevy = "0.6"
bytemuck = {version="1.7.3", features= ["derive"]}
ggrs = { git = "https://github.com/gschup/ggrs", features=["sync-send"] }
bevy_ggrs = { git = "https://github.com/gschup/bevy_ggrs" }
matchbox_socket = { path = "../matchbox/matchbox_socket", features = ["ggrs-socket"] }
log = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
ggrs = {  git = "https://github.com/gschup/ggrs", features=["sync-send", "wasm-bindgen"]}
bevy_ggrs = {  git = "https://github.com/gschup/bevy_ggrs", features=["wasm-bindgen"]}
approx = "0.5"
web-sys = "0.3"