[package]
name = "bevy_ggrs_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
bytemuck = {version="1.7.3", features= ["derive"]}
matchbox_socket = { path = "../matchbox/matchbox_socket", features = ["ggrs-socket"] }
ggrs = { git = "https://github.com/gschup/ggrs", features=["sync-send"]}
bevy_ggrs = { git = "https://github.com/gschup/bevy_ggrs"}