[package]
name = "bevy_ggrs_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
bytemuck = {version="1.7.3", features= ["derive"]}
matchbox_socket = { git = "https://github.com/johanhelsing/matchbox", features = ["ggrs-socket"] }
ggrs = { version = "0.9", features=["sync-send"]}
bevy_ggrs = "0.9"
log = "0.4"
approx = "0.5"
web-sys = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
ggrs = { version = "0.9", features=["sync-send", "wasm-bindgen"]}
bevy_ggrs = { version = "0.9", features=["wasm-bindgen"]}